### ISSUE TITLE
Small accessibility improvements

### ISSUE THREAD

**Issue by zhik** [BetaNYC/nyc-boundaries#21]
- Make all inputs forms
- Move the address search bar to the top, for better access
- Move focus to the info_box after address search or query overlapping districts is successful. Show error messages if query failed.
- Provide a link back to the search or query from the info_box

**Comment by zhik** [comment]
- Save queries in URL for better share and bookmark functionality 
e.g.
https://boundaries.beta.nyc/?lat=40.759513&lng=-73.830258
https://boundaries.beta.nyc/?boundary=cd&id=101

**Comment by evadecker** [comment]
Added in v1.0
