### ISSUE TITLE
Label and style improvements

### ISSUE THREAD

**Issue by zhik** [BetaNYC/nyc-boundaries#24]
Labels and outlines can be hidden due to overlapping of some boundary polygons. In addition some colors don't provide enough contrast from other layers and the basemap. 

![Screenshot from 2019-11-05 11-21-52](https://user-images.githubusercontent.com/9166469/68225835-0806a380-ffbf-11e9-94ef-6631d50e603e.png)

Example Community Districts and Police Precincts layer overlap in PP 114 and CD 401 resulting in only PP 114 showing. Both layers also overlap each other, which takes a few minutes to figure out the boundaries of the PP which is under CD.

**Suggested Fixes**

- Rework label styles using various `#layer::labels` [properties](https://carto.com/help/tutorials/adding-labels-to-your-map/) 
- Change outline styling to use various dotted lines, after primary colors are used (possibility make this dynamic)
- Use `ST_TRANSLATE` to shift polygons a bit to avoid overlap.

**Comment by evadecker** [comment]
Fixed in v1.0
