### ISSUE TITLE
Bugs in qry overlapping districts drop-down menu

### ISSUE THREAD

**Issue by annaminsky** [BetaNYC/nyc-boundaries#45]
When school districts is selected, 10 is listed twice in the drop-down menu, and when 22 is selected the results do not refresh.

**Comment by zhik** [comment]
@annaminsky Thanks for letting us know, looking into it.

**Comment by zhik** [comment]
Some of the polygons have [topology issues](https://gis.stackexchange.com/questions/281935/topology-exception-on-geometry-intersection), need to generate a new all_bounds.geojson file and layer.

**Comment by evadecker** [comment]
There are still two instances of School District 10 in the latest version of the map. Querying for overlaps of School District 22 now works properly: https://boundaries.beta.nyc/?map=sd&dist=22
