### ISSUE TITLE
Check tool for visual accessibility

### ISSUE THREAD

**Issue by zhik** [BetaNYC/nyc-boundaries#52]
- Contrast 
- Color-blindness

**Comment by evadecker** [comment]
Current website passes accessibility tests.

https://web.dev/measure/?url=https%3A%2F%2Fboundaries.beta.nyc

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/4117920/181524507-b033b7e7-3c4d-4a44-acbd-8b010305d0ce.png">
