### ISSUE TITLE
Congressional Districts Issue

### ISSUE THREAD

**Issue by lominsky** [BetaNYC/nyc-boundaries#69]
The Congressional Districts layer appears to have a few issues. There are some districts that no numbers appear in. Additionally, the 8th district has both a 7 and and 8 in it
<img width="898" alt="Screen Shot 2022-03-24 at 9 34 54 AM" src="https://user-images.githubusercontent.com/938686/159928768-a7108739-0c9a-4dea-824c-11dc090bdc33.png">
.

**Comment by evadecker** [comment]
This should be fixed in the latest release! https://boundaries.beta.nyc/
