### ISSUE TITLE
NYSenate Links no longer work

### ISSUE THREAD

**Issue by lavingiasa** [BetaNYC/nyc-boundaries#89]
Steps to reproduce:
- Go to https://boundaries.beta.nyc/?map=ss&dist=13
- Click the "Visit district webpage" link

Expected behavior:
- It takes you to the district webpage for district 13

Observed behavior:
- It takes you to https://www.nysenate.gov/

I'm not sure when this broke, but this might not be solvable by this tool because the nysenate website seems to be redirecting.

**Comment by lavingiasa** [comment]
Note: It does look like the link is being handled somehow because https://www.nysenate.gov/district**s**/28 takes you to a 404, but the district link redirects you.

**Comment by evadecker** [comment]
Hi @lavingiasa, sorry for the delay here! It does look like district pages on the nysenate.gov site no longer exist, and I wasn't able to find new pages for districts. I [filed an issue](https://github.com/nysenate/NYSenate.gov-Website-D9/issues/41) in the website's repo and we'll see what we hear!

**Comment by lavingiasa** [comment]
Thank you so much! I hope they are able to fix it soon :)

**Comment by routinet** [comment]
Hello again, 

I followed up on [the issue file in nysenate](https://github.com/nysenate/NYSenate.gov-Website-D9/issues/41), but thought you might be interested in an alternative.

NYSenate.gov sources its map data from another of our tools: [SAGE (Senate Address Geocoding Engine)](https://github.com/nysenate/GeoApi).  For districts, the map is embedded from a call to, e.g., `[//pubgeo.nysenate.gov/map/senate/29?x=850&y=696&sd=29](https://pubgeo.nysenate.gov/map/senate/29?x=850&y=696&sd=29).  In my brief testing, the query string parameters do not seem to be necessary.  My colleague guesses they are resolution parameters, and a redundant district marker.  In any case, it may be worth your while to go direct to the same source we use.

**Comment by evadecker** [comment]
Thanks @routinet! We already have the geojson for displaying senate boundaries on the map; what we're missing is a page that displays information about that district, who the senator is, etc.

**Comment by evadecker** [comment]
@lavingiasa A fix was merged into nysenate.gov: https://github.com/nysenate/NYSenate.gov-Website-D9/pull/46 and the links for Senate Districts are available once again! 🎉 

https://github.com/BetaNYC/nyc-boundaries/assets/4117920/2ae6daa2-acfe-416c-b54f-b535a93a02b6

**Comment by lavingiasa** [comment]
Fantastic! Thanks so much Eva for following up and to the contributors of
the other repo for fixing it

**Comment by evadecker** [comment]
Of course! Thanks for reporting it and please file issues for any other problems you come across or requests for improvements :)
